### ISSUE TITLE
show different color for high `elapsed` time

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/garnish#10]
I wonder what the simplest way of implementing this is, without making too many magical assumptions in `garnish`.

I think it might be best to defer this to the application, this way garnish doesn't assume a time unit (e.g. milliseconds) or a threshold (e.g. yellow if > 1000).

Idea 1:

```js
{ event: 'bundle', elapsed: { value: '1325 ms', color: 'yellow' } }
```

Idea 2:

```js
{ event: 'bundle', elapsed: [ '1325 ms', 'yellow' ] }
```

Idea 3 (could be named `style` instead of `color`):

```js
{ event: 'bundle', elapsed: '1325 ms', color: { elapsed: 'yellow' } }
```

I think #3 is the cleanest, and it could allow applications to style other fields like `contentLength`.

**Comment by mattdesl** [comment]
Thoughts @yoshuawuyts ?

**Comment by yoshuawuyts** [comment]
third was what I was thinking too ^^

**Comment by mattdesl** [comment]
This is now possible with the `colors` field.

**Comment by yoshuawuyts** [comment]
Amazing, didn't know that :D
