### ISSUE TITLE
default log level

### ISSUE THREAD

**Issue by yoshuawuyts** [mattdesl/garnish#13]
Right now the default log level is set to `info`. It's literally taken me 4 days + a good amount of rewrites to figure out that this was the culprit for my bug.

I think `info` as a default log level assumes too much. I'll almost always want to manage the log level from my application (either through config or cli flags), and then use garnish to prettify it. The chances that I'll want garnish to actually filter data will be sparse.

So my suggestion is to let garnish just prettify things by default (and not filter too) by changing the default log level to `debug`. What do you reckon?

**Comment by mattdesl** [comment]
Sure, fine with me. :+1:

**Comment by mattdesl** [comment]
Can probably remove the `verbose` option. It will be a major semver change.

**Comment by yoshuawuyts** [comment]
PR made. Hope it's all good ^___^
