### ISSUE TITLE
query parameters in URL

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/garnish#6]
Some other tools (beefy) just strip the query parameters when displaying the URL. Not sure if garnish should do the same to clean up logs, or whether it should be more general purpose.

<img width="567" alt="screen shot 2015-09-04 at 11 55 48 am" src="https://cloud.githubusercontent.com/assets/1383811/9688245/f3c5d234-52fb-11e5-96ca-9fdfb5849722.png">

**Comment by yoshuawuyts** [comment]
I think it's for the best if query strings and hashes are stripped, after all `garnish`'s goal is to optimize logs for human-readability.

 A while back I wrote https://github.com/yoshuawuyts/pathname-match to strip query strings / hashes, it might be useful for this scenario (':

**Comment by mattdesl** [comment]
see #9

**Comment by yoshuawuyts** [comment]
#9 was merged, think this can be closed
