### ISSUE TITLE
do not strip ansi codes

### ISSUE THREAD

**Issue by mattdesl** [mattdesl/garnish#8]
I'll have to investigate this a bit more.

Some messages like `babelify` error messages have ANSI color codes. These are stripped when piping to `garnish` which makes the output a bit bland.

**Comment by yoshuawuyts** [comment]
This should probably be tested now that 6cf7ef2 is in (':

**Comment by mattdesl** [comment]
I'm no longer seeing any issues with this when using budo + babelify. :+1:
